### ISSUE TITLE
Implement IPv6 leaks protection.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [freepn/fpnd#95]
![](https://user-images.githubusercontent.com/13170204/99244265-c1ff3500-27f9-11eb-9141-958bb588b2e3.png)

_I could, of course, just block any IPv6 traffic entirely. But that's just a way to mitigate this issue._

**Comment by sarnold** [comment]
Which version of fpnd are you running, and what is the current ``fpnd.ini`` option ``drop_ip6`` set to?  If it's already set to ``True`` then you might need to add the module cfg file to load it on boot.  See Known Issues section in the release notes: https://github.com/freepn/fpnd/blob/master/README_release-notes_latest.rst#id11

**Comment by sarnold** [comment]
Okay, I just tested ``0.9.9`` on Kali and I got an ip6_tables error starting ``fpnd`` immediately after install since the module cfg file was freshly installed and hadn't had a chance to load yet (simple fix is a reboot or manual ``modprobe`` command before starting the daemon).  Lemme see if I can find a better way to handle that case...

**Comment by sarnold** [comment]
And the "better" way works nicely on a fresh Kali install, so I'll push a new tag and update the deb packages.

**Comment by sarnold** [comment]
fixed in https://github.com/freepn/fpnd/releases/tag/0.9.10
